import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Calendar from "react-calendar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Calendar />
        </div>
      </main>
    </>
  );
}
